### ISSUE TITLE
Legislation explorer is broken

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#116]
https://openfisca-uk-explorer.herokuapp.com/ says `Application error`

**Comment by nikhilwoodruff** [comment]
Given that we're aiming to have a Python openfisca-uk web server somewhere, and the client-side UI seems easy enough to develop, I'd be in favour of adding a parameter explorer page to that site.

**Comment by MaxGhenis** [comment]
Should we use our GCP instance to host this?

**Comment by nikhilwoodruff** [comment]
Yes, I think that's a good idea
