### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#36]
I don't really like these, but here are some I made to get our gears turning in [Canva](https://www.canva.com/design/DAEnbC8LORg/share/preview?token=YhdXZzO03jOAm1FqfOTTIg&role=EDITOR&utm_content=DAEnbC8LORg&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton).

![image](https://user-images.githubusercontent.com/6076111/129837694-86d5366f-fe60-417b-b555-5fd9f1bd4671.png)
![image](https://user-images.githubusercontent.com/6076111/129837929-e4416fa7-6851-4279-9dcd-f3f02665b420.png)
![image](https://user-images.githubusercontent.com/6076111/129839857-cb14f493-db76-4792-9970-b0224ee9ba7f.png)

![2](https://user-images.githubusercontent.com/6076111/129837016-bc770cd5-e7b2-43c1-b52b-bb77b42b213f.png)
![1](https://user-images.githubusercontent.com/6076111/129837017-16533e66-8827-40a7-90db-99c116c5d841.png)

@leomatkovsky @AhmedAhmed8000 up to try some ideas?

**Comment by nikhilwoodruff** [comment]
Very much like these icons, and having the gear rotate when computing would be awesome.

**Comment by MaxGhenis** [comment]
Thanks @nmrodelo for making our current logo set:
![image](https://user-images.githubusercontent.com/6076111/139624726-76c2c2d2-bbc8-4d47-9bdb-4b2eb0f1378e.png)
![image](https://user-images.githubusercontent.com/6076111/139624756-34de2528-8c58-441c-bcdd-ea70904f6128.png)
![image](https://user-images.githubusercontent.com/6076111/139624808-66fe6072-9f59-4c1b-beef-a0519df45144.png)
![image](https://user-images.githubusercontent.com/6076111/139624812-6f332c82-34e8-41f6-a9c7-88549808547b.png)

![image](https://user-images.githubusercontent.com/6076111/139624695-2f364e5f-2810-4419-b3da-da5553853ff8.png)
Including the slogan:
![image](https://user-images.githubusercontent.com/6076111/139624718-8ecec24c-fbcd-4637-8370-225e4a6db613.png)
![image](https://user-images.githubusercontent.com/6076111/139624791-be41b31d-e33a-4a4c-a1ef-67718c514c3f.png)
