### ISSUE TITLE
Add comments to document `child_index != -1` in `UC_individual_child_element`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#440]
I don't follow this - it doesn't look like `child_index` would be negative. Naming the `child_index != -1` as a Python variable would clarify. See also #199.

https://github.com/PolicyEngine/openfisca-uk/blob/faff00791c18407bfb5b24272a793f446306818b/openfisca_uk/variables/finance/benefit/family/universal_credit.py#L153-L160

https://github.com/PolicyEngine/openfisca-uk/blob/faff00791c18407bfb5b24272a793f446306818b/openfisca_uk/variables/demographic/person.py#L104-L121

**Comment by nikhilwoodruff** [comment]
Should replace checks for -1 with checks for person("is_child", period)
