### ISSUE TITLE
Calibrate take-up rates to hit administrative targets

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#469]
We're currently using take-up rates published by government reports, but this produces discrepancies against administrative totals, especially for Universal Credit. Per @nikhilwoodruff and my conversation this morning, we'll move to instead calculate a take-up rate among people who don't report a benefit but are eligible. This rate would be calibrated to hit administrative targets.

I'd suggest we primarily work with the quantity described above (`P`), though we can relate it to the overall take-up rate (`tau`) with the below formulas. Note that I define take-up as `actual / eligible` cases, which could theoretically exceed 100%.

Seems like `P`s will be `State`-level variables, is that right?

One open question is whether to target caseload or spending. Averaging them could be ideal, but I think whichever's easiest works.

![image](https://user-images.githubusercontent.com/6076111/149608889-24d13d80-3de8-4ec0-b628-fa009c3cca14.png)

**Comment by nikhilwoodruff** [comment]
We now calibrate weights, not takeup rates.
