### ISSUE TITLE
Adjust FRS weights to match administrative statistics

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#504]
The FRS has a well-documented problem with benefit reporting and high incomes: all benefits are under-reported, as well as income sources such as dividends. Up to now, we've operated under the assumption that this is due to measurement error: that recipients are giving incorrect information about their income. However, over time I think we've discovered enough evidence to suggest it is actually mostly sampling error:
* When we calibrate takeup rates to match administrative totals, we are unable to match both caseload and expenditure statistics at the same time, suggesting that the FRS recipients are not highly representative of actual recipients. See #495.
* The [FRS questionnaire](https://sp.ukdataservice.ac.uk/doc/6523/mrdoc/pdf/frs_2008_09_gb_question_instructions.pdf) is highly detailed, with multiple checks on users' answers, and surveyors ask for documented proof of incomes. This still leaves room for error if individuals are not compliant or not aware of benefit receipt, but I doubt to the extent that the data under-reports reality (around 30%).
* UKMOD, the only other microsimulation model that publishes validation statistics, [also underestimates benefit aggregates and tax revenues](https://www.iser.essex.ac.uk/research/publications/working-papers/cempa/cempa7-20.pdf#127). Under-estimation can be caused by either incorrect data or incorrect modelling: UKMOD and OpenFisca-UK have separate implementations of the same programs, suggesting modelling is not the issue.

After some [initial trials](https://colab.research.google.com/drive/1fOKdvH4eEiM8fNXAc6KJkjW9EIZpY3oJ#scrollTo=K73JA_sycWWk), I propose an optimisation-based approach at re-weighting, using TensorFlow to optimise a weight adjustment vector in order to minimise statistical error across a range of validation statistics, penalising substantial divergence from initial weights. Essentially, we want a balance between modified weights that move us as close as possible to benefit and tax statistics, while not moving too far from the initial weights.

### Initial experimentation

The following graph illustrates the trade-off between weight edits and statistical error:
![image](https://user-images.githubusercontent.com/35577657/151721490-b5f866d8-744b-4321-a9ee-23f1bdab995d.png)

And here's an example result from one specific benefit and metric. We can get closer or further, depending on the modification penalty:
![image](https://user-images.githubusercontent.com/35577657/151721525-ce6ff145-d025-4207-822c-8eacbada1024.png)

### Process outline

We'll aim to match the following targets:
* Caseloads and aggregates for all eight major means-tested benefits, plus Income Tax and National Insurance.
* UK and regional household populations

cc @MaxGhenis

**Comment by MaxGhenis** [comment]
Some additional administrative totals to consider:
* Country-level [Income Tax](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/853118/Disaggregated_tax_and_NICs_receipts_-_methodological_note.pdf#page=14) and [NICs](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/853118/Disaggregated_tax_and_NICs_receipts_-_methodological_note.pdf#page=18) (also has things like SDLT)
* [Taxpayers by band](https://www.gov.uk/government/statistics/income-tax-liabilities-statistics-tax-year-2018-to-2019-to-tax-year-2021-to-2022/summary-statistics)
* [Taxpayers, income, and income tax by income range](https://docs.google.com/spreadsheets/d/1tFQNlaDjeEwsxtwfYBUNzZtLcpG1Izy7N0R3V-83mlU/edit?usp=sharing)
* [Population by age and gender](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland)
* [Various DWP totals via Stat-Xplore, including their API](https://stat-xplore.dwp.gov.uk/webapi/online-help/Open-Data-API-Table.html)

**Comment by nikhilwoodruff** [comment]
Thanks, got all but the last two. I can't seem to find a source for the 5-year age bins in years other than 2020, and I am wondering whether we should include them given they don't uprate directly *upwards* but mostly *along* in future years.
