### ISSUE TITLE
Average by epoch in validation graph to avoid oscillation

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#508]
From https://policyengine.github.io/openfisca-uk//model/reweighting.html#loss-characteristic-by-training-epoch, this occurs because it's showing multiple years in each epoch, filter to a single year, or add animation frame by year:

![image](https://user-images.githubusercontent.com/6076111/152578849-584c97eb-7290-4bfb-b3a6-a3ba781cbd77.png)

**Comment by nikhilwoodruff** [comment]
No longer an issue, as the current training process steps through all years at each epoch.
