### ISSUE TITLE
Remove y axis title from validation chart

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#514]
Missed out from #513

**Comment by MaxGhenis** [comment]
While you're in there, could you also move OpenFisca-UK above UKMOD ([while preserving the legend order](https://stackoverflow.com/a/62611337/1840471)) and add the sign of the error to the hovercard?

I think we could also lead with the graph and have the tables default to hidden via the `hide-cell` tag.
