### ISSUE TITLE
Run imputation after re-weighting

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#569]
This should improve the accuracy of the wealth imputations from the Wealth and Assets Survey to the Family Resources Survey.

### Technical details

Currently, for every wealth variable in the WAS (e.g. main residence value), we build a model that predicts the distribution of that variable from a set of variables that the FRS also has. We then sample from the midpoint of that distribution, and calibrate the FRS weights so that the total wealth values from the ONS are matched in the imputations.

It would be more accurate to perform the calibration without wealth imputations, and then sample from the *x*th percentile of the wealth distributions such that we hit the targets, as this will likely enable us to hit all targets (including tax/benefit targets) better.

The implementation for this is in progress in #568.

**Comment by MaxGhenis** [comment]
Would this affect the LCFS imputations, or do those already follow the reweighting?

**Comment by nikhilwoodruff** [comment]
Right now the weight calibration is the final step, so yes.

**Comment by MaxGhenis** [comment]
Full ideal sequence:
* ExtendedFRS: Quadruple records for UC/legacy and FRS/SPI imputation
* CalibratedFRS: Uprate ExtendedFRS and reweight for every year through 2026
* EnhancedFRS: Imputes from uprated WAS and LCFS, creates versions for each year to drop zero-weight records each year

**Comment by nikhilwoodruff** [comment]
This is now completely fixed by #566
