### ISSUE TITLE
Cliff for family of four from £50,200 to £50,300 income

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#575]
Is this right? From PolicyEngine, married 2 kids.
<img width="921" alt="image" src="https://user-images.githubusercontent.com/6076111/163416639-17877704-3f32-4c57-b6d2-01b5030c08c9.png">

**Comment by nikhilwoodruff** [comment]
This is the marriage allowance - lost when you reach the higher rate threshold. Unfortunately a feature, not a bug.
