### ISSUE TITLE
Phase out full family's UBI

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#576]
Currently, the UBI phase-out only applies to the primary household member's UBI. For example, here's how a [£200/week UBI for all age groups phasing out at 50%](https://policyengine.org/uk/household?adult_bi=200&child_bi=200&senior_bi=200&bi_phase_out_rate=50) affects a married family with two children:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/6076111/163418929-b7a116f8-a2dd-451f-81c5-a7b5897c20b2.png">

The MTR change stops at £20,800, which is double the primary earner's UBI (due to 50% phase-out):
<img width="929" alt="image" src="https://user-images.githubusercontent.com/6076111/163419110-b363d8ce-a268-401f-ac0b-de7bbf7df892.png">

This occurs because the [`bi_phaseout` variable](https://github.com/PolicyEngine/openfisca-uk/blob/master/openfisca_uk/variables/contrib/ubi_center/basic_income/bi_phaseout.py) is at the person level.

**Comment by nikhilwoodruff** [comment]
* Change parameter description to clarify this is individual
* Add household-level phase-out based on combined income
