### ISSUE TITLE
Licence fee

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#615]
£159/year per household

Per https://www.tvlicensing.co.uk/check-if-you-need-one/topics/tv-licence-types-and-costs-top2:
* [If you’re aged 74 and over](https://www.tvlicensing.co.uk/check-if-you-need-one/for-your-home/aged-74-and-over-aud3) and you, or your partner living at the same address receive Pension Credit, you could get a free licence.
* If you live in a [care home or sheltered accommodation](https://www.tvlicensing.co.uk/check-if-you-need-one/for-your-home/care-home-residents-aud4) you may be able to pay a discounted fee of £7.50.
* If you’re [blind (severely sight impaired)](https://www.tvlicensing.co.uk/check-if-you-need-one/for-your-home/blindseverely-sight-impaired-aud5) you can apply to pay half of the licence fee (£79.50)
* If you only watch on a [black and white TV](https://www.tvlicensing.co.uk/faqs/FAQ236), the licence costs £53.50.

[£3.75bn revenue in 2020/21](https://commonslibrary.parliament.uk/research-briefings/cbp-8101/#:~:text=TV%20licence%20fee%20revenues%20in,around%2074%25%20of%20total%20income.)

**Comment by nikhilwoodruff** [comment]
Now implemented.
