### ISSUE TITLE
Households are over-represented by 6%

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#617]
Running locally I get 29.6m households, compared to the [28.5m total from the ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/families/datasets/familiesandhouseholdsfamiliesandhouseholds). We should fix this by adding more importance to this loss metric.

**Comment by MaxGhenis** [comment]
How many households do we have now?

**Comment by nikhilwoodruff** [comment]
Huh. It's now at 9% (31.3m). I just took a look at the actual loss components and I think it's because the total household counts for each of the local area targets sums to more than the ONS household counts for the entire UK. I'm adding in an adjustment which scales down each local target by the relative difference when added up.

**Comment by nikhilwoodruff** [comment]
Now fixed at ~3%.
