### ISSUE TITLE
Pension Credit does not deduct all Income Tax payments

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#618]
Pension Credit is not deducting all Income Tax payments (just those over the personal allowance), causing an underestimation. Verified with the household earnings distribution calculator on PolicyEngine below:
![image](https://user-images.githubusercontent.com/35577657/180659608-b66bf274-620b-478e-9152-b0d41aa57e3a.png).

**Comment by MaxGhenis** [comment]
Could you share a screenshot of the graph with the fix?
