### ISSUE TITLE
MTR chart in individual documentation page is broken

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#632]
https://policyengine.github.io/openfisca-uk//usage/individuals.html

<img width="713" alt="image" src="https://user-images.githubusercontent.com/6076111/190872793-bc54700d-1b2e-4415-ac6c-28e0560f2f63.png">

Similarly broken at https://policyengine.github.io/openfisca-uk//usage/graphs.html

<img width="748" alt="image" src="https://user-images.githubusercontent.com/6076111/190872784-877986b1-ec75-4794-9e3f-b7652f1d9988.png">

**Comment by nikhilwoodruff** [comment]
Ah it'll be the TV licence
