### ISSUE TITLE
End health and social care levy

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#652]
>From 6 November 2022, the temporary 1.25 percentage point increase in National Insurance rates is being reversed for the rest of the financial year.

https://www.gov.uk/guidance/prepare-for-the-health-and-social-care-levy

**Comment by rasoolsomji** [comment]
Fixed by https://github.com/PolicyEngine/policyengine-uk/commit/e9a4507607c45e6a3bd1b7cb765d46211a28e0f3?

**Comment by nikhilwoodruff** [comment]
Ah yes good catch.
