### ISSUE TITLE
Clarify UC takeup rate parameter

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#711]
The takeup rate parameter is misleading: we assign takeup based on reported survey claims of UC. Here's how we use the takeup rate parameter in the model:

* If a household is an entitled non-takeup household in the baseline, they don't claim UC in the reform either
* If a household is entitled to UC in the baseline and claims it, they also claim it in the reform unless taken out of entitlement
* If a household isn't entitled to UC in the baseline but is moved into entitlement by a reform, they are (e.g.) 70% likely to begin to claim UC (where 70% is the takeup rate)

We should make clear that increasing the takeup rate doesn't affect baseline non-claimants.

**Comment by nikhilwoodruff** [comment]
We now don't use this parameter in favour of using reported status and reweighting in the data stage. So the current metadata is misleading. We should add another parameter _assume full takeup_ and remove this one. We'll implement and have it live on the app by Monday 26th February.

**Comment by nikhilwoodruff** [comment]
FYI @catheroni @lukastk

**Comment by catheroni** [comment]
@nikhilwoodruff was this implemented?

**Comment by nikhilwoodruff** [comment]
Apologies for the late action on this and #820 (tied up with other priorities). We'll aim to have them in by the end of the week. In the meantime I'd suggest a) not using this parameter and b) avoiding income-based ESA in reforms, or modifying the repo to include the simulated values if you're able to.

**Comment by nikhilwoodruff** [comment]
We now use an actual take up rate parameter.
