### ISSUE TITLE
Set LHA to 30th percentile from April 2024

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#785]
As announced in the Autumn Budget https://assets.publishing.service.gov.uk/media/655d0a83544aea000dfb321d/Autumn_Statement_2023_Policy_Costings_-_Final.pdf#page=16

Seems like this would require several changes including #105 #106

**Comment by nikhilwoodruff** [comment]
Found the List of Rents we can use. [2021](https://www.gov.uk/government/publications/local-housing-allowance-list-of-rents-2023-24) is the most recent, but we can uprate with the rental price [index](https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/indexofprivatehousingrentalprices/october2023#uk-private-rental-prices).
