### ISSUE TITLE
Add aging routine

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#79]
To get data to current year

**Comment by nikhilwoodruff** [comment]
We should use this as reference: [UKMOD uprating factors](https://www.iser.essex.ac.uk/research/publications/working-papers/cempa/cempa7-20.pdf#page=109)

**Comment by nikhilwoodruff** [comment]
In progress as of https://github.com/nikhilwoodruff/family-resources-survey/pull/1

**Comment by MaxGhenis** [comment]
Is this done?

**Comment by nikhilwoodruff** [comment]
We've got some basic aging on labour and capital income variables, but I think this could benefit from comparing to UKMOD and ensuring consistency (keeping open).

**Comment by MaxGhenis** [comment]
Done
