### ISSUE TITLE
Add person_weight to household attributes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#88]
As `household_weight * people_in_household`, used for calculating things like deciles and inequality metrics.

**Comment by nikhilwoodruff** [comment]
I think this might actually just introduce confusion to be honest: right now if you do 
```python
sim.calc("people", map_to="household")
```
It'll return a MicroSeries whose weighted values are the person weights of households. (or ```person_weight``` for the actual values).
