### ISSUE TITLE
Deprecated `pension_income` variable doesn't behave correctly

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-uk#908]
At least within the SPI model calibration code (draft PR #902), adding pension income to the model as the `pension_income` variable has no impact on net pension income, but adding it as `private_pension_income` correctly calculates the value. `pension_income`, though theoretically deprecated, should still return the same value as `private_pension_income`.

**Comment by nikhilwoodruff** [comment]
We've now removed it from the data so I think this is completed?
