### ISSUE TITLE
Adjust private school VAT attendance probabilities

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-uk#957]
Currently we are too high- 800k children, when it's probably [closer to 600k](https://www.isc.co.uk/media/uukn4r3i/isc_census_2024_15may24.pdf).

We impute based on fixed probabilities by income percentile, plus an adjustment factor to get an exact match to a number. We should adjust the factor, seems like it's outdated in recent data iterations. We should also add a test to make sure that the private school child count stays within e.g. 15% of the target.

**Comment by MaxGhenis** [comment]
Why not reweight for it again?

**Comment by vahid-ahmadi** [comment]
I added a test to get the best adjustment factor (which is 0.77). The test file's name is "solve_private_school_attendance_factor.py".

**Comment by nikhilwoodruff** [comment]
@MaxGhenis reweight for each of the percentiles? Could do, but the current approach enforces the income correlation well.

**Comment by MaxGhenis** [comment]
I see. But do we do this probability before or after reweighting? If before should we target the total in reweighting?

@vahid-ahmadi I see you added that in #959, which looks good! Should we close this issue then? In the future please link PRs to issues to close them automatically. In general each PR should link to at least one issue.

**Comment by vahid-ahmadi** [comment]
Sure, I got it.

**Comment by nikhilwoodruff** [comment]
Fixed by #959
